name: .NET

env:
  registryName: wthngdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}
  devWebApp: wthngdevops-dev

on:
  push:
    paths: 'Application/**'
    #branches: [ main ]
  pull_request:
    paths: 'Application/**'

jobs:
  build: #Name of job1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore 
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj


  docker: #Name of job 2
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login $registryName -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag

      #challenge 6
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      uses: azure/webapps-deploy@v2
    - name: Pull Container Image
      with:
        app-name: ${{ env.devWebApp }}
        images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}