name: .NET

env:
  registryName: wthngdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPth: Application/aspnet-core-dotnet-core
  tag: ${{github.run_number}}

on:
  push:
    paths: 'Application/**'
    #branches: [ main ]
  pull_request:
    paths: 'Application/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore 
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login $registryName -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag
